access:
  - 'ck save'
  - 'ck settings'
  - 'ench add'
  - 'ench remove'
access-mess:
  - 'you cannot do it now!'
save-mess:
  - 'done'
edit-mess:
  - 'edit now'
editing-place: 0, 100.0, 0, 0, 90, world