name: CustomKit
version: '${project.version}'
main: dev.timury.customkit.CustomKit
api-version: '1.17'
depend: [ StrikePractice ]
authors: [ Timury ]
commands:
  ck:
    description: the StrikeCustomGamemode command
    permission: CKA.customkit
  ench:
    description: the StrikeCustomGamemode command
    permission: CKA.customkit
